# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/svn/trunk/src/bserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/svn/trunk/src/bserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/svn/trunk/src/bserver/CMakeFiles /root/svn/trunk/src/bserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/svn/trunk/src/bserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/b_server

# Build rule for target.
bin/b_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/b_server
.PHONY : bin/b_server

# fast build rule for target.
bin/b_server/fast:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/build
.PHONY : bin/b_server/fast

# target to build an object file
embeded_python/python_call_base.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/embeded_python/python_call_base.o
.PHONY : embeded_python/python_call_base.o

# target to preprocess a source file
embeded_python/python_call_base.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/embeded_python/python_call_base.i
.PHONY : embeded_python/python_call_base.i

# target to generate assembly for a file
embeded_python/python_call_base.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/embeded_python/python_call_base.s
.PHONY : embeded_python/python_call_base.s

# target to build an object file
embeded_python/python_func_service_responser.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/embeded_python/python_func_service_responser.o
.PHONY : embeded_python/python_func_service_responser.o

# target to preprocess a source file
embeded_python/python_func_service_responser.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/embeded_python/python_func_service_responser.i
.PHONY : embeded_python/python_func_service_responser.i

# target to generate assembly for a file
embeded_python/python_func_service_responser.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/embeded_python/python_func_service_responser.s
.PHONY : embeded_python/python_func_service_responser.s

# target to build an object file
embeded_python/python_status_ensure.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/embeded_python/python_status_ensure.o
.PHONY : embeded_python/python_status_ensure.o

# target to preprocess a source file
embeded_python/python_status_ensure.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/embeded_python/python_status_ensure.i
.PHONY : embeded_python/python_status_ensure.i

# target to generate assembly for a file
embeded_python/python_status_ensure.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/embeded_python/python_status_ensure.s
.PHONY : embeded_python/python_status_ensure.s

# target to build an object file
httpclient/curl_base.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/curl_base.o
.PHONY : httpclient/curl_base.o

# target to preprocess a source file
httpclient/curl_base.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/curl_base.i
.PHONY : httpclient/curl_base.i

# target to generate assembly for a file
httpclient/curl_base.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/curl_base.s
.PHONY : httpclient/curl_base.s

# target to build an object file
httpclient/server_service_response_responser.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/server_service_response_responser.o
.PHONY : httpclient/server_service_response_responser.o

# target to preprocess a source file
httpclient/server_service_response_responser.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/server_service_response_responser.i
.PHONY : httpclient/server_service_response_responser.i

# target to generate assembly for a file
httpclient/server_service_response_responser.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/server_service_response_responser.s
.PHONY : httpclient/server_service_response_responser.s

# target to build an object file
httpclient/server_service_responser.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/server_service_responser.o
.PHONY : httpclient/server_service_responser.o

# target to preprocess a source file
httpclient/server_service_responser.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/server_service_responser.i
.PHONY : httpclient/server_service_responser.i

# target to generate assembly for a file
httpclient/server_service_responser.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/server_service_responser.s
.PHONY : httpclient/server_service_responser.s

# target to build an object file
httpclient/service_package_busy_responser.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/service_package_busy_responser.o
.PHONY : httpclient/service_package_busy_responser.o

# target to preprocess a source file
httpclient/service_package_busy_responser.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/service_package_busy_responser.i
.PHONY : httpclient/service_package_busy_responser.i

# target to generate assembly for a file
httpclient/service_package_busy_responser.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/service_package_busy_responser.s
.PHONY : httpclient/service_package_busy_responser.s

# target to build an object file
httpclient/service_package_responser.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/service_package_responser.o
.PHONY : httpclient/service_package_responser.o

# target to preprocess a source file
httpclient/service_package_responser.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/service_package_responser.i
.PHONY : httpclient/service_package_responser.i

# target to generate assembly for a file
httpclient/service_package_responser.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/httpclient/service_package_responser.s
.PHONY : httpclient/service_package_responser.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/main.s
.PHONY : main.s

# target to build an object file
proto/ServicePacket.pb.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/proto/ServicePacket.pb.o
.PHONY : proto/ServicePacket.pb.o

# target to preprocess a source file
proto/ServicePacket.pb.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/proto/ServicePacket.pb.i
.PHONY : proto/ServicePacket.pb.i

# target to generate assembly for a file
proto/ServicePacket.pb.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/proto/ServicePacket.pb.s
.PHONY : proto/ServicePacket.pb.s

# target to build an object file
proto/connect_server.pb.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/proto/connect_server.pb.o
.PHONY : proto/connect_server.pb.o

# target to preprocess a source file
proto/connect_server.pb.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/proto/connect_server.pb.i
.PHONY : proto/connect_server.pb.i

# target to generate assembly for a file
proto/connect_server.pb.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/proto/connect_server.pb.s
.PHONY : proto/connect_server.pb.s

# target to build an object file
src/client_session.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/client_session.o
.PHONY : src/client_session.o

# target to preprocess a source file
src/client_session.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/client_session.i
.PHONY : src/client_session.i

# target to generate assembly for a file
src/client_session.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/client_session.s
.PHONY : src/client_session.s

# target to build an object file
src/configwrap.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/configwrap.o
.PHONY : src/configwrap.o

# target to preprocess a source file
src/configwrap.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/configwrap.i
.PHONY : src/configwrap.i

# target to generate assembly for a file
src/configwrap.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/configwrap.s
.PHONY : src/configwrap.s

# target to build an object file
src/heart_task_thread.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/heart_task_thread.o
.PHONY : src/heart_task_thread.o

# target to preprocess a source file
src/heart_task_thread.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/heart_task_thread.i
.PHONY : src/heart_task_thread.i

# target to generate assembly for a file
src/heart_task_thread.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/heart_task_thread.s
.PHONY : src/heart_task_thread.s

# target to build an object file
src/json_parser.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/json_parser.o
.PHONY : src/json_parser.o

# target to preprocess a source file
src/json_parser.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/json_parser.i
.PHONY : src/json_parser.i

# target to generate assembly for a file
src/json_parser.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/json_parser.s
.PHONY : src/json_parser.s

# target to build an object file
src/json_push_packet.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/json_push_packet.o
.PHONY : src/json_push_packet.o

# target to preprocess a source file
src/json_push_packet.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/json_push_packet.i
.PHONY : src/json_push_packet.i

# target to generate assembly for a file
src/json_push_packet.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/json_push_packet.s
.PHONY : src/json_push_packet.s

# target to build an object file
src/log.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/log.o
.PHONY : src/log.o

# target to preprocess a source file
src/log.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/log.i
.PHONY : src/log.i

# target to generate assembly for a file
src/log.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/log.s
.PHONY : src/log.s

# target to build an object file
src/logic_deal_processing.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/logic_deal_processing.o
.PHONY : src/logic_deal_processing.o

# target to preprocess a source file
src/logic_deal_processing.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/logic_deal_processing.i
.PHONY : src/logic_deal_processing.i

# target to generate assembly for a file
src/logic_deal_processing.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/logic_deal_processing.s
.PHONY : src/logic_deal_processing.s

# target to build an object file
src/message_format.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/message_format.o
.PHONY : src/message_format.o

# target to preprocess a source file
src/message_format.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/message_format.i
.PHONY : src/message_format.i

# target to generate assembly for a file
src/message_format.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/message_format.s
.PHONY : src/message_format.s

# target to build an object file
src/peer_base.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_base.o
.PHONY : src/peer_base.o

# target to preprocess a source file
src/peer_base.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_base.i
.PHONY : src/peer_base.i

# target to generate assembly for a file
src/peer_base.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_base.s
.PHONY : src/peer_base.s

# target to build an object file
src/peer_handle_client.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_handle_client.o
.PHONY : src/peer_handle_client.o

# target to preprocess a source file
src/peer_handle_client.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_handle_client.i
.PHONY : src/peer_handle_client.i

# target to generate assembly for a file
src/peer_handle_client.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_handle_client.s
.PHONY : src/peer_handle_client.s

# target to build an object file
src/peer_handle_map.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_handle_map.o
.PHONY : src/peer_handle_map.o

# target to preprocess a source file
src/peer_handle_map.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_handle_map.i
.PHONY : src/peer_handle_map.i

# target to generate assembly for a file
src/peer_handle_map.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_handle_map.s
.PHONY : src/peer_handle_map.s

# target to build an object file
src/peer_handle_server.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_handle_server.o
.PHONY : src/peer_handle_server.o

# target to preprocess a source file
src/peer_handle_server.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_handle_server.i
.PHONY : src/peer_handle_server.i

# target to generate assembly for a file
src/peer_handle_server.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/peer_handle_server.s
.PHONY : src/peer_handle_server.s

# target to build an object file
src/server_session.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/server_session.o
.PHONY : src/server_session.o

# target to preprocess a source file
src/server_session.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/server_session.i
.PHONY : src/server_session.i

# target to generate assembly for a file
src/server_session.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/server_session.s
.PHONY : src/server_session.s

# target to build an object file
src/service_request_json_data.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/service_request_json_data.o
.PHONY : src/service_request_json_data.o

# target to preprocess a source file
src/service_request_json_data.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/service_request_json_data.i
.PHONY : src/service_request_json_data.i

# target to generate assembly for a file
src/service_request_json_data.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/service_request_json_data.s
.PHONY : src/service_request_json_data.s

# target to build an object file
src/service_response_result.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/service_response_result.o
.PHONY : src/service_response_result.o

# target to preprocess a source file
src/service_response_result.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/service_response_result.i
.PHONY : src/service_response_result.i

# target to generate assembly for a file
src/service_response_result.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/service_response_result.s
.PHONY : src/service_response_result.s

# target to build an object file
src/session_base.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/session_base.o
.PHONY : src/session_base.o

# target to preprocess a source file
src/session_base.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/session_base.i
.PHONY : src/session_base.i

# target to generate assembly for a file
src/session_base.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/session_base.s
.PHONY : src/session_base.s

# target to build an object file
src/session_task.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/session_task.o
.PHONY : src/session_task.o

# target to preprocess a source file
src/session_task.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/session_task.i
.PHONY : src/session_task.i

# target to generate assembly for a file
src/session_task.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/session_task.s
.PHONY : src/session_task.s

# target to build an object file
src/task_base.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/task_base.o
.PHONY : src/task_base.o

# target to preprocess a source file
src/task_base.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/task_base.i
.PHONY : src/task_base.i

# target to generate assembly for a file
src/task_base.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/task_base.s
.PHONY : src/task_base.s

# target to build an object file
src/task_responser.o:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/task_responser.o
.PHONY : src/task_responser.o

# target to preprocess a source file
src/task_responser.i:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/task_responser.i
.PHONY : src/task_responser.i

# target to generate assembly for a file
src/task_responser.s:
	$(MAKE) -f CMakeFiles/bin/b_server.dir/build.make CMakeFiles/bin/b_server.dir/src/task_responser.s
.PHONY : src/task_responser.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bin/b_server"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... embeded_python/python_call_base.o"
	@echo "... embeded_python/python_call_base.i"
	@echo "... embeded_python/python_call_base.s"
	@echo "... embeded_python/python_func_service_responser.o"
	@echo "... embeded_python/python_func_service_responser.i"
	@echo "... embeded_python/python_func_service_responser.s"
	@echo "... embeded_python/python_status_ensure.o"
	@echo "... embeded_python/python_status_ensure.i"
	@echo "... embeded_python/python_status_ensure.s"
	@echo "... httpclient/curl_base.o"
	@echo "... httpclient/curl_base.i"
	@echo "... httpclient/curl_base.s"
	@echo "... httpclient/server_service_response_responser.o"
	@echo "... httpclient/server_service_response_responser.i"
	@echo "... httpclient/server_service_response_responser.s"
	@echo "... httpclient/server_service_responser.o"
	@echo "... httpclient/server_service_responser.i"
	@echo "... httpclient/server_service_responser.s"
	@echo "... httpclient/service_package_busy_responser.o"
	@echo "... httpclient/service_package_busy_responser.i"
	@echo "... httpclient/service_package_busy_responser.s"
	@echo "... httpclient/service_package_responser.o"
	@echo "... httpclient/service_package_responser.i"
	@echo "... httpclient/service_package_responser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... proto/ServicePacket.pb.o"
	@echo "... proto/ServicePacket.pb.i"
	@echo "... proto/ServicePacket.pb.s"
	@echo "... proto/connect_server.pb.o"
	@echo "... proto/connect_server.pb.i"
	@echo "... proto/connect_server.pb.s"
	@echo "... src/client_session.o"
	@echo "... src/client_session.i"
	@echo "... src/client_session.s"
	@echo "... src/configwrap.o"
	@echo "... src/configwrap.i"
	@echo "... src/configwrap.s"
	@echo "... src/heart_task_thread.o"
	@echo "... src/heart_task_thread.i"
	@echo "... src/heart_task_thread.s"
	@echo "... src/json_parser.o"
	@echo "... src/json_parser.i"
	@echo "... src/json_parser.s"
	@echo "... src/json_push_packet.o"
	@echo "... src/json_push_packet.i"
	@echo "... src/json_push_packet.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/logic_deal_processing.o"
	@echo "... src/logic_deal_processing.i"
	@echo "... src/logic_deal_processing.s"
	@echo "... src/message_format.o"
	@echo "... src/message_format.i"
	@echo "... src/message_format.s"
	@echo "... src/peer_base.o"
	@echo "... src/peer_base.i"
	@echo "... src/peer_base.s"
	@echo "... src/peer_handle_client.o"
	@echo "... src/peer_handle_client.i"
	@echo "... src/peer_handle_client.s"
	@echo "... src/peer_handle_map.o"
	@echo "... src/peer_handle_map.i"
	@echo "... src/peer_handle_map.s"
	@echo "... src/peer_handle_server.o"
	@echo "... src/peer_handle_server.i"
	@echo "... src/peer_handle_server.s"
	@echo "... src/server_session.o"
	@echo "... src/server_session.i"
	@echo "... src/server_session.s"
	@echo "... src/service_request_json_data.o"
	@echo "... src/service_request_json_data.i"
	@echo "... src/service_request_json_data.s"
	@echo "... src/service_response_result.o"
	@echo "... src/service_response_result.i"
	@echo "... src/service_response_result.s"
	@echo "... src/session_base.o"
	@echo "... src/session_base.i"
	@echo "... src/session_base.s"
	@echo "... src/session_task.o"
	@echo "... src/session_task.i"
	@echo "... src/session_task.s"
	@echo "... src/task_base.o"
	@echo "... src/task_base.i"
	@echo "... src/task_base.s"
	@echo "... src/task_responser.o"
	@echo "... src/task_responser.i"
	@echo "... src/task_responser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

